---
deployment:
  tasks:
    - export APPPATH=/home/heavwzih/develop.heavenlymatch.net

    - cd $APPPATH && composer install --no-dev --optimize-autoloader --no-interaction

    - cd $APPPATH && mkdir -p storage/framework/views storage/framework/cache/data storage/framework/sessions bootstrap/cache

    - cd $APPPATH && php artisan migrate --force

    - cd $APPPATH && php artisan storage:link || true

    - chmod -R 775 $APPPATH/storage $APPPATH/bootstrap/cache || true

    - cd $APPPATH && php artisan optimize:clear

    - cd $APPPATH && php artisan config:cache
    - cd $APPPATH && php artisan route:cache || true
    - cd $APPPATH && php artisan view:cache