---
deployment:
  tasks:
    - export DEPLOYPATH=/home/heavwzih/develop.heavenlymatch.net/
    - /bin/rsync -av --delete --exclude='.git' --exclude='.env' --exclude='node_modules' --exclude='storage/logs' --exclude='storage/framework/cache' --exclude='storage/framework/sessions' --exclude='storage/framework/views' ./ $DEPLOYPATH
    - cd $DEPLOYPATH && /usr/local/bin/php artisan optimize:clear
    - cd $DEPLOYPATH && /usr/local/bin/php artisan config:cache
    - cd $DEPLOYPATH && /usr/local/bin/php artisan route:cache
    - cd $DEPLOYPATH && /usr/local/bin/php artisan view:cache