deployment:
  tasks:
    - export DEPLOYPATH=/home/heavwzih/public_html
    - /usr/local/bin/composer install --no-dev --optimize-autoloader
    - php artisan migrate --force
    - php artisan config:cache
    - php artisan route:cache
    - php artisan storage:link
    - chmod -R 775 storage bootstrap/cache
